#!/usr/bin/env python3
"""
Convert GeoGebra Asymptote to parameterized LINE_THICKNESS and DOT_THICKNESS.

Usage:
    python ggb_to_param_asy.py input.asy > output.asy
"""

import re
import sys
import argparse
from pathlib import Path

DEFAULT_SIZE = "12cm"
DEFAULT_FONTSIZE = 7.5
DEFAULT_LSF = None
DEFAULT_LINE_THICKNESS = 0.5
DEFAULT_DOT_THICKNESS = 2.0

HDR_TEMPLATE = """import graph;
size({size});

real lsf = {lsf_val};
real labelscalefactor = lsf;
real fontsize_base = {fontsize};
real LINE_THICKNESS = {line_thickness};
real DOT_THICKNESS = {dot_thickness};

defaultpen(linewidth(LINE_THICKNESS) + fontsize(fontsize_base));
pen dotstyle = linewidth(DOT_THICKNESS) + black;

picture pic;
"""

# Regex optimizations
LSF_RE = re.compile(r"\breal\s+(?:lsf|labelscalefactor)\s*=\s*([^;]+);")
HEADER_REMOVAL_RE = re.compile(
    r"\bpen\s+dps\s*=\s*[^;]+;\s*|"
    r"\bdefaultpen\s*\(\s*dps\s*\)\s*;\s*|"
    r"\bimport\s+graph\s*;\s*|"
    r"\bsize\s*\([^;]+\)\s*;\s*|"
    r"\breal\s+(?:lsf|labelscalefactor)\s*=\s*[^;]+;\s*|"
    r"\bdefaultpen\s*\([^;]+\)\s*;\s*|"
    r"\bpen\s+dotstyle\s*=\s*[^;]+;\s*",
    flags=re.IGNORECASE
)
LINEWIDTH_RE = re.compile(r"linewidth\(\s*[\d.]+(?:pt)?\s*\)")
DOT_STYLE_RE = re.compile(
    r"dot\(\s*(.*?)\s*,\s*(?:linewidth\([^)]*\)\s*\+\s*)?(?:dotstyle|ds|dp)\s*\)",
    flags=re.DOTALL
)

# Negative lookahead prevents duplicating "pic, " if the command already has it
DRAW_CMD_RE = re.compile(r"\b(filldraw|draw|dot|label|xaxis|yaxis|clip)\s*\(\s*(?!pic\s*,)")

# Scrubs mathematical artifacts generated by GeoGebra
INFINITY_RE = re.compile(r"^.*Infinity.*$\n?", flags=re.MULTILINE)
BLANK_LINES_RE = re.compile(r"\n{3,}")


def transform(
    text: str, 
    fontsize: float, 
    lsf_override: str | None, 
    line_thickness: str, 
    dot_thickness: str, 
    size: str
) -> str:
    # Sanitize input to remove hidden non-breaking spaces (e.g., \xa0)
    text = text.replace('\xa0', ' ')

    lsf_match = LSF_RE.search(text)
    lsf_val = lsf_override.strip() if lsf_override else (lsf_match.group(1).strip() if lsf_match else "0.1")

    header = HDR_TEMPLATE.format(
        lsf_val=lsf_val,
        fontsize=f"{fontsize:g}",
        line_thickness=line_thickness,
        dot_thickness=dot_thickness,
        size=size,
    )

    # Apply substitutions
    body = HEADER_REMOVAL_RE.sub("", text)
    body = INFINITY_RE.sub("", body)
    body = LINEWIDTH_RE.sub("linewidth(LINE_THICKNESS)", body)
    body = DOT_STYLE_RE.sub(r"dot(\1, dotstyle)", body)
    body = DRAW_CMD_RE.sub(r"\1(pic, ", body)
    
    # Clean up redundant add(pic) calls and excess newlines
    body = re.sub(r"\badd\s*\(\s*pic\s*\)\s*;\s*", "", body)
    body = BLANK_LINES_RE.sub("\n\n", body).strip()

    return f"{header}\n{body}\n\nadd(pic);\n// created by ggbparse.py\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Rewrite GeoGebra-exported .asy to use paramaterized thicknesses.")
    parser.add_argument("input", type=Path, help="Input .asy filename")
    parser.add_argument("-size", "--size", type=str, default=DEFAULT_SIZE, help=f"Figure size (default: {DEFAULT_SIZE})")
    parser.add_argument("-font", "--fontsize", type=float, default=DEFAULT_FONTSIZE, help=f"Base fontsize (default: {DEFAULT_FONTSIZE})")
    parser.add_argument("-lsf", "--lsf", type=str, default=DEFAULT_LSF, help="Override label scale factor")
    parser.add_argument("-line", "--line-thickness", type=str, default=str(DEFAULT_LINE_THICKNESS), help=f"LINE_THICKNESS (default: {DEFAULT_LINE_THICKNESS})")
    parser.add_argument("-dot", "--dot-thickness", type=str, default=str(DEFAULT_DOT_THICKNESS), help=f"DOT_THICKNESS (default: {DEFAULT_DOT_THICKNESS})")

    args = parser.parse_args()

    try:
        text: str = args.input.read_text(encoding="utf-8")
        sys.stdout.write(
            transform(
                text=text,
                fontsize=args.fontsize,
                lsf_override=args.lsf,
                line_thickness=args.line_thickness,
                dot_thickness=args.dot_thickness,
                size=args.size,
            )
        )
    except Exception as e:
        sys.exit(f"Error reading '{args.input}': {e}")


if __name__ == "__main__":
    main()